"""Stages 1-3: ingest, change analysis, risk engine. All deterministic.

No model is consulted in this package. Stage 1 is the only place that talks to
GitHub; stages 2 and 3 work purely from the normalized `PullRequest`.
"""

from __future__ import annotations

from .change_analyzer import (
    ATTRIBUTION_TIERS,
    AttributionTier,
    ChangeAnalysis,
    ChangeAnalyzer,
    ChangeGroup,
    ChangeScope,
    FileChange,
    SourceLookup,
    analyze,
)
from .ingest import (
    ChangedFile,
    CredentialsRejected,
    GitHubIngest,
    GitHubResponse,
    GitHubTransport,
    GitHubUnavailable,
    IngestError,
    InsufficientPermissions,
    MalformedResponse,
    PullRequest,
    PullRequestNotFound,
    RateLimited,
    RepoConfig,
    RepositoryNotFound,
    UrllibTransport,
    fetch_pull_request,
)
from .source import (
    CheckoutSource,
    GitArchiveMaterializer,
    GitCloneMaterializer,
    InMemorySource,
    Materializer,
    ReviewWorkspace,
    SourceProvider,
    WorkspaceError,
    open_workspace,
)
from .risk import (
    DEPTH_BY_LEVEL,
    RISK_LEVELS,
    RISK_ORDER,
    RiskAssessment,
    RiskEngine,
    RiskLevel,
    RiskPolicy,
    RiskSignal,
    assess,
    controls_for,
)

__all__ = [
    "ATTRIBUTION_TIERS",
    "DEPTH_BY_LEVEL",
    "RISK_LEVELS",
    "RISK_ORDER",
    "AttributionTier",
    "ChangeAnalysis",
    "ChangeAnalyzer",
    "ChangeGroup",
    "ChangeScope",
    "ChangedFile",
    "CheckoutSource",
    "CredentialsRejected",
    "FileChange",
    "GitArchiveMaterializer",
    "GitCloneMaterializer",
    "GitHubIngest",
    "GitHubResponse",
    "GitHubTransport",
    "GitHubUnavailable",
    "IngestError",
    "InMemorySource",
    "InsufficientPermissions",
    "MalformedResponse",
    "Materializer",
    "PullRequest",
    "PullRequestNotFound",
    "RateLimited",
    "RepoConfig",
    "RepositoryNotFound",
    "ReviewWorkspace",
    "RiskAssessment",
    "RiskEngine",
    "RiskLevel",
    "RiskPolicy",
    "RiskSignal",
    "SourceLookup",
    "SourceProvider",
    "UrllibTransport",
    "WorkspaceError",
    "analyze",
    "assess",
    "controls_for",
    "fetch_pull_request",
    "open_workspace",
]
